OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: ShippingOrg1
    Domain: shipping.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 3

  - Name: DistributorOrg2
    Domain: distributor.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 3

  - Name: PharmacyOrg3
    Domain: pharmacy.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 3
